### ISSUE TITLE
Variables almost invesible when selected [C#]

### ISSUE THREAD

**Issue by crimcol** [FINNSEEFLY/Darcula-Theme-VS-2022#12]
When you double-click on any word (variable, property, method name) Visual studio will highlight the same substring in the file.
In this case, the highlighting background color is almost the same as font color:
![image](https://user-images.githubusercontent.com/4273048/206822719-ede8ce45-11ec-4ad2-a7d7-28f1374a3e8c.png)

Would be nice to tweak the substring highlighting the background color.

**Comment by FINNSEEFLY** [comment]
I have tried to rework some points in the highlighting in version 1.1.0. I hope everything will be fine now👌
