### ISSUE TITLE
xml the text color is dark.

### ISSUE THREAD

**Issue by pvich70** [FINNSEEFLY/Darcula-Theme-VS-2022#14]
The color text on xml files is black, with the dark gray background it is difficult to read.
For the rest it works nice, thank you.

![image](https://user-images.githubusercontent.com/20019941/208616731-060e51e3-5965-4696-968b-e5b0579a0a0b.png)

**Comment by FINNSEEFLY** [comment]
Well, I tried to reproduce this issue as follows:
1. Created a file with the XML extension.
2. Wrote some XML.
3. Wrote XML similar to what is in the screenshot.

The result looks like this:
![xml example](https://user-images.githubusercontent.com/43048277/209161801-58ddf1d4-a6f1-4112-8525-1673bd37e4c7.png)


As you can see, the syntax highlighting was correct.

The check was performed in the following environment:
- Visual Studio 2022 version: **17.4.3**
- Extension version: **1.1.0**
- Is the resharper installed: **tested with and without it**

Please check if everything is updated and if the problem persists, give me more context when and how it is reproduced.

**Comment by pvich70** [comment]
This one was a xamarin AndroidManifest.xml, the one created by VS.

AndoirdManifest.xml
![image](https://user-images.githubusercontent.com/20019941/209392217-041425df-4501-4014-b1fd-6ba14c33cb0d.png)

new project:
![image](https://user-images.githubusercontent.com/20019941/209392891-535ac409-714e-4aef-bc75-648939ace76e.png)


activity_main.xmls
![image](https://user-images.githubusercontent.com/20019941/209392303-c332f05a-fffe-4319-a595-f4f1665c79ff.png)


However, if I create a new single xml file it works perfect. I copy paste the same xml on a new xml file and it looks nice.
![image](https://user-images.githubusercontent.com/20019941/209392570-17c338b6-eb91-442e-a6ba-d721d7b8da7b.png)

**Comment by FINNSEEFLY** [comment]
In version 1.1.1, I made changes that should fix this. I tested it on one of my old Xamarin projects and it worked for me. I hope this will work for you too👌. 

If the problem persists, please reopen this issue.
