### ISSUE TITLE
Font Color Almost Matches Background

### ISSUE THREAD

**Issue by JoshuaCichoski** [FINNSEEFLY/Darcula-Theme-VS-2022#16]
Hi there, love this theme!
I noticed that the CodeLens links to "Run" or "Debug" are in a font color that almost matches the background. Honestly, I dug through VS 2022 settings to see if I could change it locally so I could give a better description here and have no idea where these are buried. 
![image](https://user-images.githubusercontent.com/4561355/211417882-96e3eda3-991b-4e69-9925-0a2b2f244f0f.png)
![image](https://user-images.githubusercontent.com/4561355/211417942-7912caef-4264-4268-ae46-3e7bf8be1f99.png)

**Comment by FINNSEEFLY** [comment]
Hi
A bit later than planned, but fixed!
