### ISSUE TITLE
Theme not working for Intel oneAPI

### ISSUE THREAD

**Issue by wxinix-2022** [FINNSEEFLY/Darcula-Theme-VS-2022#20]
If the vcproject has the following specified, the theme won't be applied.  

Any idea?

<PlatformToolset>Intel(R) oneAPI DPC++ Compiler 2023</PlatformToolset>

**Comment by FINNSEEFLY** [comment]
Greetings
I apologize for such a long reply. If you are still interested in making this work, please provide more information.
- What components were installed with Visual Studio?
- What type of projects are being used?
- What 3rd party extensions are installed?
- Any other useful information in the form of code snippets, screenshots, etc.

_If this is no longer relevant to you, you can just close this issue._
