### ISSUE TITLE
Typo underline squiggles are close to impossible to see

### ISSUE THREAD

**Issue by OddMathisenNOV** [FINNSEEFLY/Darcula-Theme-VS-2022#23]
When having typos in a project, the dark blue squiggle color of a typo almost disappears in the background color of the Darcula theme.

As an example:
![image](https://github.com/FINNSEEFLY/Darcula-Theme-VS-2022/assets/136710383/ddf06af2-f8d2-4b7f-bad5-93cf769cba2a)
This image has a one-character typo squiggle correlated to some typos related to the namespace.
I spent more than I'd like to admit trying to find the underlined error. I only found it after switching back to the normal VS dark theme.

I propose changing this color to something more vibrant.

**Comment by FINNSEEFLY** [comment]
Thanks a lot for the information!
Hope it's finally fixed in 1.1.4
