### ISSUE TITLE
High Contrast on Sticky Scroll Headers with Dracula Theme

### ISSUE THREAD

**Issue by dengyakui** [FINNSEEFLY/Darcula-Theme-VS-2022#29]
## Issue Type
Feature Request

## Description
Greetings,

I've been enjoying the Dracula theme for Visual Studio 2022; it's been a respite for my eyes during long coding sessions! However, I've encountered a minor aesthetic issue that contrasts the overall seamless experience.

When I enable the Sticky Scroll feature (`Tools` -> `Options` -> `Text Editor` -> `General` -> `Sticky scroll` the section headers that "stick" to the top upon scrolling have a background color that stands out against the rest of the theme, creating a visually jarring experience.
you can view it in below images.

## Expected Behavior
Sticky headers blend smoothly with the overall theme, providing a consistent color theme from top to bottom and not visually separating from the rest of the code editor.

## Actual Behavior
The sticky headers' background color has a high contrast compared to the warm, dark color scheme of the Dracula theme.

## Suggestion
It would be wonderful if the theme could include styles for the Sticky Scroll headers that align with the Dracula color scheme. Alternatively, providing an option for users to customize the sticky header colors could also be a great solution.

I believe other enthusiasts and I would greatly appreciate this enhancement, as it'll make the coding environment even more comfortable and visually appealing.

Thank you for considering this request! I look forward to potential updates and am more than willing to assist in testing any changes if needed.

![2024-04-18_14-29-23](https://github.com/FINNSEEFLY/Darcula-Theme-VS-2022/assets/3945919/bf8576b7-e880-4ee7-9726-c6e90936dbbe)

**Comment by FINNSEEFLY** [comment]
Hey there! Thanks for reaching out and providing the details. I've made the necessary fixes and it's now available in version 1.1.7. Let me know if you have any further questions or concerns
